url: https://amicitia65.github.io
baseurl: /koduleht1.0/

# Site settings
title: Korporatsioon Amicitia
email: kirjatoimetaja@amicitia.ee
description: "Korp! Amicitia on tegusaid ja vahvaid eesti naisüliõpilasi 
              ühendav korporatsioon, mis on asutatud 1924. aastal. Meie eesmärgiks on pakkuda 
              oma liikmetele võimalusi enesearenduseks ja eneseteostuseks ning põnevat elu 
              väljaspool loenguid ja eksameid."


# Team names, titles and social links
people:
- name: Janne Lamus 
  pic: 4
  position: Kirjatoimetaja
  social:
    - title: envelope
      url: mailto:kirjatoimetaja@amicitia.ee

- name: Heli Vahar
  pic: 4
  position: Esinaine
  social:
    - title: envelope
      url: mailto:esinaine@amicitia.ee

- name: Inge-Mirjam Piirsalu
  pic: 4
  position: Abiesinaine
  social:
    - title: envelope
      url: mailto:abiesinaine@amicitia.ee

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/korpamicitia/
  - title: facebook
    url: https://www.facebook.com/korpamicitia

# Postal address (add as many lines as necessary)
address: Kastani 65-2, Tartu 50410

# Build settings
markdown: kramdown
permalink: pretty